const perfumesData = [
    { name: 'Sauvage', brand: 'Dior', image: 'dior/sauv.avif', price: 750 },
    { name: 'Fahrenheit', brand: 'Dior', image: 'dior/fahr.avif', price: 450 },
    { name: 'No. 5', brand: 'Chanel', image: 'chanel/n5.avif', price: 650 },
    { name: 'Coco Mademoiselle', brand: 'Chanel', image: 'chanel/cocom.avif', price: 1350 },
    { name: 'Oud Wood', brand: 'Tom Ford', image: 'tom-ford/oudwood.avif', price: 1350 },
    { name: 'Lost Cherry', brand: 'Tom Ford', image: 'tom-ford/lost-cherry.avif', price: 1350 },
    { name: 'Tobacco Vanille', brand: 'Tom Ford', image: 'tom-ford/tobacco.avif', price: 1350 },
    { name: 'Vanille Fattale', brand: 'Tom Ford', image: 'tom-ford/vanille-fatale.avif', price: 1350 },
    { name: 'Black Lacquer', brand: 'Tom Ford', image: 'tom-ford/lacquer.avif', price: 1350 },
    { name: 'Oajan', brand: 'Parfums de Marly', image: 'marly/oajan.avif', price: 1050 },
    { name: 'Layton', brand: 'Parfums de Marly', image: 'marly/layton.avif', price: 1050 },
    { name: 'Althair', brand: 'Parfums de Marly', image: 'marly/althair.avif', price: 1090 },
    { name: 'Haltane', brand: 'Parfums de Marly', image: 'marly/haltane.avif', price: 1050 },
    { name: 'Kalan', brand: 'Parfums de Marly', image: 'marly/kalan.avif', price: 1050 },
    { name: 'Aventus', brand: 'Creed', image: 'creed/av.avif', price: 1550 },
    { name: 'Royal Oud', brand: 'Creed', image: 'creed/ro.avif', price: 1550 },
    { name: 'Original Vetiver', brand: 'Creed', image: 'creed/veti.avif', price: 1475 },
    { name: 'Silver Mountain Water', brand: 'Creed', image: 'creed/sm.avif', price: 1475 },
    { name: 'Dia Woman', brand: 'Amouage', image: 'amouage/dw.avif', price: 1825 },
    { name: 'Honour Woman', brand: 'Amouage', image: 'amouage/hw.avif', price: 1825 },
    { name: 'Interlude Man', brand: 'Amouage', image: 'amouage/im.avif', price: 1825 },
    { name: 'Reflection Man', brand: 'Amouage', image: 'amouage/rm.avif', price: 1825 },
    { name: 'Terre d Hermès', brand: 'Hermès', image: 'hermes/terre.avif', price: 545 },
    { name: 'Eau des Merveilles', brand: 'Hermès', image: 'hermes/merv.avif', price: 890 },
    { name: 'Un Jardin Sur Le Neil', brand: 'Hermès', image: 'hermes/jardin.avif', price: 500 },
    { name: 'Santal 33', brand: 'Le Labo', image: 'labo/s33.jpg', price: 1025 },
    { name: 'Another 13', brand: 'Le Labo', image: 'labo/a33.jpg', price: 1025 },
    { name: 'Rose 31', brand: 'Le Labo', image: 'labo/r31.jpg', price: 1025 },
    { name: 'Bergamote 22', brand: 'Le Labo', image: 'labo/b22.jpg', price: 1025 },
    { name: 'Baccarat Rouge 540', brand: 'Maison Francis Kurkdjian', image: 'mf/rose.png', price: 1050 },
    { name: 'À la rose', brand: 'Maison Francis Kurkdjian', image: 'mf/rouge.png', price: 1050 },
    { name: 'Grand Soir', brand: 'Maison Francis Kurkdjian', image: 'mf/soir.png', price: 1050 },
    { name: 'Aqua Universalis', brand: 'Maison Francis Kurkdjian', image: 'mf/aqua.png', price: 1050 },
    { name: 'Wood & Spices', brand: 'Montale', image: 'mont/spices.avif', price: 525 },
    { name: 'Black Aoud', brand: 'Montale', image: 'mont/aoud.avif', price: 525 },
    { name: 'Intense Café', brand: 'Montale', image: 'mont/cafe.avif', price: 525 },
    { name: '+22+', brand: 'Chrome Hearts', image: 'ch/22.png', price: 2350 },
    { name: '+33+', brand: 'Chrome Hearts', image: 'ch/33.png', price: 2350 }
  ];
  
  export default perfumesData;
  